### ISSUE TITLE
Using compression format "raw" throws CompilerException

### ISSUE THREAD

**Issue by arimer** [bmuschko/gradle-izpack-plugin#17]
Using latest plugin in version `3.2` and setting the [compression property](https://github.com/bmuschko/gradle-izpack-plugin#convention-properties) as suggested to `raw` fails with the following exception:

```
[ant:izpack] Exception in thread "Thread-35" com.izforge.izpack.api.exception.CompilerException: Unknown compression format: raw
[ant:izpack]    at com.izforge.izpack.ant.IzpackAntRunnable.run(IzpackAntRunnable.java:82)
[ant:izpack]    at java.base/java.lang.Thread.run(Thread.java:834)
[ant:izpack] Caused by: com.izforge.izpack.api.exception.CompilerException: Unknown compression format: raw
[ant:izpack]    at com.izforge.izpack.compiler.CompilerConfig.addInfoStrings(CompilerConfig.java:2548)
[ant:izpack]    at com.izforge.izpack.compiler.CompilerConfig.executeCompiler(CompilerConfig.java:343)
[ant:izpack]    at com.izforge.izpack.ant.IzpackAntRunnable.run(IzpackAntRunnable.java:78)
[ant:izpack]    ... 1 more
```

**Comment by bmuschko** [comment]
Looks like a [breaking changes](https://izpack.atlassian.net/wiki/spaces/IZPACK/pages/491591/Compiling+Using+Ant) was introduced with IzPack 5.0.

> compression:
Optional compression format for single files defined in <packs>. All files in all packs except those explicitly marked as <pack200/> are automatically added compressed in the given format and uncompressed later when the installer starts. This may significantly decrease the installer size, but take some more time to compile the installer and install the files later.
See also [Compressing pack files](https://izpack.atlassian.net/wiki/spaces/IZPACK/pages/67078184/Compressing+pack+files) for more information on this feature.
Possible values: default | gz | bzip2 | xz | lzma | deflate
Default: default (uncompressed)
Since: IzPack 5.1 (has been broken in 5.0)

The value for the `compression` field should become a non-validated field to ensure that a range of IzPack version will work with the plugin. Care you send a pull request?
